---
platforms:
  - name: podman_rhel9
    image: registry.access.redhat.com/ubi9/ubi-init
    pre_build_image: true
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    # capabilities:
    #   - SYS_ADMIN
    published_ports:
      # - "127.0.0.1:19050:10050/tcp"
      - "19050:10050/tcp"
      - "19020:10020/tcp"
    command: "/usr/sbin/init"
    groups:
      - molecule
      - podman
      - linux
      - rhel
      - yum

  - name: podman_cs9
    dockerfile: ../default/files/Dockerfile.rhel.j2
    image: quay.io/centos/centos:stream9
    pre_build_image: false
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    capabilities:
      - SYS_ADMIN
    published_ports:
      - "19350:10050/tcp"
      - "19320:10020/tcp"
    # exposed_ports:
    #   - "22018/tcp"
    command: "/usr/sbin/init"
    groups:
      - molecule
      - podman
      - linux
      - centos
      - yum

  - name: podman_ora9
    dockerfile: ../default/files/Dockerfile.rhel.j2
    image: docker.io/library/oraclelinux:9
    pre_build_image: false
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    # capabilities:
    #   - SYS_ADMIN
    published_ports:
      - "19450:10050/tcp"
      - "19420:10020/tcp"
    # exposed_ports:
    #   - "22018/tcp"
    command: "/usr/sbin/init"
    groups:
      - molecule
      - podman
      - linux
      - oracle
      - yum

  - name: podman_alma9
    dockerfile: ../default/files/Dockerfile.rhel.j2
    image: docker.io/library/almalinux:9
    pre_build_image: false
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    # capabilities:
    #   - SYS_ADMIN
    published_ports:
      - "19150:10050/tcp"
      - "19120:10020/tcp"
    command: "/usr/sbin/init"
    groups:
      - molecule
      - podman
      - linux
      - alma
      - yum

  - name: podman_rocky9
    dockerfile: ../default/files/Dockerfile.rhel.j2
    image: docker.io/library/rockylinux:9
    pre_build_image: false
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    # capabilities:
    #   - SYS_ADMIN
    published_ports:
      - "19250:10050/tcp"
      - "19220:10020/tcp"
    command: "/usr/sbin/init"
    groups:
      - molecule
      - podman
      - linux
      - rocky
      - yum

  - name: podman_ubuntu22
    dockerfile: ../default/files/Dockerfile.ubuntu.j2
    image: docker.io/library/ubuntu:22.04
    pre_build_image: false
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    capabilities:
      - SYS_ADMIN
    published_ports:
      - "12250:10050/tcp"
      - "12220:10020/tcp"
    command: "/usr/sbin/init"
    groups:
      - molecule
      - podman
      - linux
      - ubuntu
      - apt

  - name: podman_debian12
    image: docker.io/library/debian:12
    dockerfile: ../default/files/Dockerfile.debian.j2
    pre_build_image: false
    # tmpfs:
    #   - /run
    #   - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
    capabilities:
      - SYS_ADMIN
    published_ports:
      - "11250:10050/tcp"
      - "11220:10020/tcp"
    command: "/lib/systemd/systemd"
    groups:
      - molecule
      - podman
      - linux
      - debian
      - apt
